apiVersion: v1
data:
  PASSWORD: {{ .Values.PASSWORD | b64enc }} #Y2ljZF9kYl91c2Vy #YWRtaW5AMTIz
  USERNAME: {{ .Values.USERNAME | b64enc }} #Y2ljZF9kYl91c2Vy #cm9vdA==
kind: Secret
metadata:
  name: sqldb-secret
type: Opaque