apiVersion: v1
kind: Service
metadata:
  name: cicd-frontend-service
  labels:
    {{- include "cicd-image-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.frontendtype }}
  ports:
    - port: 3003
      targetPort: {{ .Values.service.frontendport }}
      protocol: TCP
      
  selector:
    {{- include "cicd-image-deployment.selectorLabels" . | nindent 4 }}
    version: {{ .Values.image.tag }}
   
---
   
apiVersion: v1
kind: Service
metadata:
  name: cicd-backend-service
  labels:
    {{- include "cicd-image-deployment.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backendtype }}
  ports:
    - port: 3001
      targetPort: {{ .Values.service.backendport }}
      protocol: TCP
  selector:
    {{- include "cicd-image-deployment.selectorLabels" . | nindent 4 }}
    version: {{ .Values.image.tag }}    
